/**
 * ============================================================
 *  Bihar Land Records & Esports — Hindi Transliteration Library
 *  Auto-translation word dictionary for in-site use
 *  Generated for: Net2coder / Sitamarhi-region project
 * ============================================================
 *
 *  Usage:
 *    import { directWords, transliterateWord, transliterateText } from "./transliteration-library";
 *
 *  directWords  — the raw lookup map (string → Devanagari)
 *  transliterateWord(word)  — transliterate a single Latin word
 *  transliterateText(text)  — transliterate a full sentence / paragraph
 */

// ─────────────────────────────────────────────────────────────
// 1. DIRECT WORD MAP
// ─────────────────────────────────────────────────────────────

export const directWords: Record<string, string> = {

  // ── Directions ─────────────────────────────────────────────
  amin: "अमीन",
  anchal: "अंचल",
  bihar: "बिहार",
  dakshin: "दक्षिण",
  decimal: "डिसमिल",
  jila: "जिला",
  jamabandi: "जमाबंदी",
  khata: "खाता",
  khesra: "खेसरा",
  kumar: "कुमार",
  mauja: "मौजा",
  mouza: "मौजा",
  malik: "मालिक",
  paschim: "पश्चिम",
  patna: "पटना",
  purab: "पूर्व",
  purv: "पूर्व",
  raiyat: "रैयत",
  thana: "थाना",
  uttar: "उत्तर",
  west: "पश्चिम",
  east: "पूर्व",
  north: "उत्तर",
  south: "दक्षिण",
  pashchim: "पश्चिम",
  dakhin: "दक्षिण",
  madhya: "मध्य",
  center: "केंद्र",
  nagla: "नगला",

  // ── Land & Measurements ────────────────────────────────────
  bigha: "बीघा",
  katha: "कट्ठा",
  kattha: "कट्ठा",
  dhur: "धुर",
  dhurki: "धुर्की",
  furki: "फुर्की",
  laggie: "लग्गी",
  laggi: "लग्गी",
  dismil: "डिसमिल",
  rakba: "रकबा",
  hissa: "हिस्सा",
  batwara: "बंटवारा",
  chauhaddi: "चौहद्दी",
  chauhadhi: "चौहद्दी",
  sarhadi: "सरहदी",
  zamin: "ज़मीन",
  jamin: "जमीन",
  plot: "प्लॉट",
  kadi: "कड़ी",
  jarib: "जरीब",
  acre: "एकड़",
  hectare: "हेक्टेयर",
  square: "वर्ग",
  meter: "मीटर",
  foot: "फुट",
  gunta: "गुंटा",
  marla: "मर्ला",
  satak: "शतक",
  chatak: "छटाक",
  seeng: "सींग",
  latha: "लठ्ठा",
  gaj: "गज",
  hasta: "हस्त",
  kos: "कोस",
  mile: "मील",
  paisa: "पैसा",
  kanal: "कनाल",
  rod: "रॉड",
  chain: "चेन",

  // ── Land Types & Documents ─────────────────────────────────
  bakasht: "बकाश्त",
  gairmazarua: "गैरमजरुआ",
  aam: "आम",
  khas: "खास",
  kaimi: "कैमी",
  sikmi: "सिकमी",
  khatiyan: "खतियान",
  khatiyani: "खतियानी",
  dakhil: "दाखिल",
  kharij: "खारिज",
  kewala: "केवाला",
  bainama: "बैनामा",
  hukumnama: "हुक्मनामा",
  pattidari: "पट्टेदारी",
  bataidari: "बटाईदारी",
  dakhilkharij: "दाखिल-खारिज",
  rasid: "रसीद",
  raseed: "रसीद",
  patta: "पट्टा",
  lagan: "लगान",
  malguzari: "मालगुज़ारी",
  lagaan: "लगान",
  bandobast: "बंदोबस्त",
  settlement: "बंदोबस्त",
  mutation: "दाखिल-खारिज",
  registry: "रजिस्ट्री",
  noksha: "नक्शा",
  naksha: "नक्शा",
  tatima: "तातिमा",
  nisbat: "निस्बत",
  virasat: "विरासत",
  wirasat: "विरासत",
  wasiyat: "वसीयत",
  waseeyat: "वसीयत",
  deed: "विलेख",
  lease: "पट्टा",
  rent: "किराया",
  mortgage: "बंधक",
  bandhan: "बंधन",
  rahn: "रहन",
  girvee: "गिरवी",
  bai: "बय",
  wasool: "वसूल",
  mafi: "माफी",
  chakbandi: "चकबंदी",
  consolidation: "चकबंदी",
  khewat: "खेवट",
  khatauni: "खतौनी",
  misal: "मिसल",
  fard: "फर्द",
  copy: "नकल",
  nakal: "नकल",
  certified: "प्रमाणित",
  attested: "सत्यापित",
  dum: "दम",
  survey: "सर्वेक्षण",
  sarvekshan: "सर्वेक्षण",
  khasra: "खसरा",

  // ── Administrative / Government ───────────────────────────
  panchayat: "पंचायत",
  prakhand: "प्रखंड",
  anumandal: "अनुमंडल",
  zila: "जिला",
  zilla: "जिला",
  halka: "हल्का",
  karmachari: "कर्मचारी",
  kanoongo: "कानूनगो",
  sarpanch: "सरपंच",
  mukhiya: "मुखिया",
  circle: "सर्कल",
  bdo: "बीडीओ",
  co: "सीओ",
  sdo: "एसडीओ",
  dclr: "डीसीएलआर",
  gram: "ग्राम",
  gaon: "गाँव",
  gaw: "गाँव",
  tola: "टोला",
  mohalla: "मोहल्ला",
  ward: "वार्ड",
  post: "पोस्ट",
  patti: "पट्टी",
  parishad: "परिषद",
  pramanpatra: "प्रमाणपत्र",
  adesh: "आदेश",
  sarkar: "सरकार",
  rajya: "राज्य",
  desh: "देश",
  shahar: "शहर",
  nagar: "नगर",
  municipality: "नगर पालिका",
  nagarpalika: "नगर पालिका",
  corporation: "निगम",
  nigam: "निगम",
  collector: "कलेक्टर",
  dm: "डीएम",
  sp: "एसपी",
  sdm: "एसडीएम",
  tehsil: "तहसील",
  tehsildar: "तहसीलदार",
  patwari: "पटवारी",
  lekhpal: "लेखपाल",
  rajaswa: "राजस्व",
  revenue: "राजस्व",
  vibhag: "विभाग",
  department: "विभाग",
  karmalay: "कार्यालय",
  karyalay: "कार्यालय",
  office: "कार्यालय",
  aayog: "आयोग",
  commission: "आयोग",
  court: "न्यायालय",
  nyayalay: "न्यायालय",
  tribunal: "अधिकरण",
  adhikaran: "अधिकरण",
  judge: "न्यायाधीश",
  adhikari: "अधिकारी",
  officer: "अधिकारी",
  inspector: "निरीक्षक",
  nirikshak: "निरीक्षक",
  number: "संख्या",
  sankhya: "संख्या",
  date: "तिथि",
  tithi: "तिथि",
  year: "वर्ष",
  varsh: "वर्ष",
  saal: "साल",
  month: "माह",
  maah: "माह",
  masik: "मासिक",
  din: "दिन",
  day: "दिन",
  time: "समय",
  samay: "समय",
  aaj: "आज",
  kal: "कल",
  parso: "परसों",
  application: "आवेदन",
  avedan: "आवेदन",
  form: "प्रपत्र",
  prappatra: "प्रपत्र",
  certificate: "प्रमाण पत्र",
  pramaan: "प्रमाण",
  report: "प्रतिवेदन",
  prativedhan: "प्रतिवेदन",
  challan: "चालान",
  notice: "नोटिस",
  order: "आदेश",
  reply: "जवाब",
  jawab: "जवाब",
  complaint: "शिकायत",
  shikayat: "शिकायत",
  petition: "याचिका",
  yachika: "याचिका",

  // ── Sitamarhi District Places ──────────────────────────────
  sitamarhi: "सीतामढ़ी",
  dumra: "डुमरा",
  riga: "रीगा",
  runnisaidpur: "रुन्नीसैदपुर",
  bairgania: "बैरगनिया",
  sonbarsa: "सोनबरसा",
  sursand: "सुरसंड",
  bajpatti: "बाजपट्टी",
  pupri: "पुपरी",
  belsand: "बेलसंड",
  parsauni: "परसौनी",
  majhorganj: "मेजरगंज",
  nanpur: "नानपुर",
  bokhara: "बोखरा",
  choraut: "चोरौत",
  bathnaha: "बथनाहा",
  parihar: "परिहार",
  suppi: "सुप्पी",
  muzaffarpur: "मुजफ्फरपुर",
  sheohar: "शिवहर",
  seohar: "शिवहर",
  darbhanga: "दरभंगा",
  madhubani: "मधुबनी",
  motihari: "मोतिहारी",
  samastipur: "समस्तीपुर",
  mejorganj: "मेजरगंज",
  majorganj: "मेजरगंज",

  // ── Bihar Districts (Complete) ─────────────────────────────
  araria: "अररिया",
  arwal: "अरवल",
  aurangabad: "औरंगाबाद",
  banka: "बाँका",
  begusarai: "बेगूसराय",
  bhagalpur: "भागलपुर",
  bhojpur: "भोजपुर",
  buxar: "बक्सर",
  gaya: "गया",
  gopalganj: "गोपालगंज",
  jamui: "जमुई",
  jehanabad: "जहानाबाद",
  kaimur: "कैमूर",
  katihar: "कटिहार",
  khagaria: "खगड़िया",
  kishanganj: "किशनगंज",
  lakhisarai: "लखीसराय",
  madhepura: "मधेपुरा",
  munger: "मुंगेर",
  nalanda: "नालंदा",
  nawada: "नवादा",
  purnea: "पूर्णिया",
  rohtas: "रोहतास",
  saharsa: "सहरसा",
  saran: "सारण",
  sheikhpura: "शेखपुरा",
  siwan: "सीवान",
  supaul: "सुपौल",
  vaishali: "वैशाली",
  west_champaran: "पश्चिम चम्पारण",
  east_champaran: "पूर्वी चम्पारण",

  // ── Major Bihar Cities / Towns ─────────────────────────────
  chapra: "छपरा",
  hajipur: "हाजीपुर",
  ara: "आरा",
  sasaram: "सासाराम",
  dehri: "डेहरी",
  bettiah: "बेतिया",
  siwan_city: "सीवान",
  chhapra: "छपरा",
  danapur: "दानापुर",
  barh: "बाढ़",
  mokameh: "मोकामा",
  lakhisarai_city: "लखीसराय",
  nawada_city: "नवादा",
  gaya_city: "गया",
  bodh: "बोध",
  rajgir: "राजगीर",
  pawapuri: "पावापुरी",
  jehanabad_city: "जहानाबाद",
  arwal_city: "अरवल",
  biharsharif: "बिहारशरीफ",
  islampur: "इस्लामपुर",
  hilsa: "हिलसा",
  ekangarsarai: "एकंगरसराय",
  digha: "दीघा",
  panapur: "पानापुर",
  forbesganj: "फारबिसगंज",
  jogbani: "जोगबनी",
  jamalpur: "जमालपुर",
  sultanganj: "सुल्तानगंज",
  kahalgaon: "कहलगाँव",
  banka_city: "बाँका",
  deoghar: "देवघर",

  // ── Village Names (Majorganj / Sitamarhi area) ─────────────
  akhardiha: "अखरडीहा",
  bahera: "बहेरा",
  barahi: "बराही",
  hari: "हरि",
  bariarpur: "बरियारपुर",
  basbita: "बसबिटा",
  belwa: "बेलवा",
  parri: "पररी",
  bhilwahi: "भिलवाही",
  bhokraha: "भोकराहा",
  bisambharpur: "बिसंभरपुर",
  nankar: "नानकार",
  dumri: "डुमरी",
  kalan: "कलां",
  kala: "कलां",
  madhuban: "मधुबन",
  jadu: "जादू",
  khurd: "खुर्द",
  garhwa: "गढ़वा",
  bishunpur: "बिशुनपुर",
  halimpur: "हलीमपुर",
  hanumannagar: "हनुमाननगर",
  harpur: "हरपुर",
  hinrolwa: "हिंरोलवा",
  parsotim: "परसोतिम",
  khairwa: "खैरवा",
  kuari: "कुआरी",
  madan: "मदन",
  madhopur: "माधोपुर",
  malinia: "मलिनिया",
  marpa: "मरपा",
  sirpal: "सिरपाल",
  mejar: "मेजर",
  ganj: "गंज",
  malahi: "मलाझी",
  pachharwa: "पचहरवा",
  pacharwa: "पचहरवा",
  raghunathpur: "रघुनाथपुर",
  rampat: "रामपत",
  pakri: "पकरी",
  rasulpur: "रसूलपुर",
  pitaunjia: "पितौंजिया",
  ratanpur: "रतनपुर",
  sonaul: "सोनौल",
  mahodat: "महोदत",

  // ── Honorifics / Titles / Relations ───────────────────────
  shri: "श्री",
  shrimati: "श्रीमती",
  srimati: "श्रीमती",
  shree: "श्री",
  shreemati: "श्रीमती",
  devi: "देवी",
  prasad: "प्रसाद",
  singh: "सिंह",
  ram: "राम",
  das: "दास",
  yadav: "यादव",
  mandal: "मंडल",
  sharma: "शर्मा",
  mishra: "मिश्रा",
  jha: "झा",
  thakur: "ठाकुर",
  sah: "साह",
  sahu: "साहू",
  chaudhary: "चौधरी",
  paswan: "पासवान",
  manjhi: "मांझी",
  beta: "बेटा",
  beti: "बेटी",
  putra: "पुत्र",
  putri: "पुत्री",
  pita: "पिता",
  mata: "माता",
  patni: "पत्नी",
  pati: "पति",
  dada: "दादा",
  dadi: "दादी",
  nana: "नाना",
  nani: "नानी",
  sasur: "ससुर",
  saas: "सास",
  bhai: "भाई",
  bahan: "बहन",
  urf: "उर्फ",
  wasi: "वासी",
  niwasi: "निवासी",
  sakin: "साकिन",
  hissedar: "हिस्सेदार",
  sahib: "साहब",
  mahoday: "महोदय",
  janab: "जनाब",
  sri: "श्री",
  dr: "डॉ",
  prof: "प्रो",
  adv: "अधिवक्ता",
  advocate: "अधिवक्ता",
  engineer: "अभियंता",
  abhiyanta: "अभियंता",
  swargiya: "स्वर्गीय",
  late: "स्वर्गीय",
  marhoom: "मरहूम",
  chacha: "चाचा",
  chachi: "चाची",
  mama: "मामा",
  mami: "मामी",
  mausa: "मौसा",
  mausi: "मौसी",
  bhanji: "भांजी",
  bhanja: "भांजा",
  bhatija: "भतीजा",
  bhatiji: "भतीजी",
  damad: "दामाद",
  bahu: "बहू",
  devar: "देवर",
  devrani: "देवरानी",
  jeth: "जेठ",
  jethani: "जेठानी",
  nanad: "ननद",
  sali: "साली",
  sala: "साला",

  // ── Male First Names ───────────────────────────────────────
  amit: "अमित",
  aman: "अमन",
  anil: "अनिल",
  ankit: "अंकित",
  arun: "अरुण",
  ashok: "अशोक",
  ashish: "आशीष",
  abhishek: "अभिषेक",
  binod: "बिनोद",
  brij: "बृज",
  bharat: "भरत",
  bhola: "भोला",
  bablu: "बबलू",
  bittu: "बिट्टू",
  binit: "बिनीत",
  birendra: "बीरेंद्र",
  chandan: "चंदन",
  chhotu: "छोटू",
  chandra: "चंद्र",
  deepak: "दीपक",
  dinesh: "दिनेश",
  dharmendra: "धर्मेंद्र",
  devendra: "देवेंद्र",
  gautam: "गौतम",
  ganesh: "गणेश",
  gopal: "गोपाल",
  golu: "गोलू",
  harish: "हरीश",
  himanshu: "हिमांशु",
  indra: "इंद्र",
  ishan: "ईशान",
  jitendra: "जितेंद्र",
  jay: "जय",
  jagdish: "जगदीश",
  kishore: "किशोर",
  kisan: "किसन",
  kishan: "किशन",
  krishn: "कृष्ण",
  krishna: "कृष्णा",
  kapil: "कपिल",
  karan: "करन",
  kunal: "कुणाल",
  lalu: "लालू",
  lalan: "ललन",
  lakshman: "लक्ष्मण",
  manoj: "मनोज",
  mukesh: "मुकेश",
  manish: "मनीष",
  mohan: "मोहन",
  mahendra: "महेंद्र",
  naveen: "नवीन",
  navin: "नवीन",
  narendra: "नरेंद्र",
  nitish: "नीतीश",
  nitesh: "नितेश",
  neeraj: "नीरज",
  omprakash: "ओमप्रकाश",
  om: "ओम",
  pankaj: "पंकज",
  pramod: "प्रमोद",
  pradeep: "प्रदीप",
  pradip: "प्रदीप",
  prashant: "प्रशांत",
  prem: "प्रेम",
  pawan: "पवन",
  pappu: "पप्पू",
  pintu: "पिंटू",
  raju: "राजू",
  raj: "राज",
  rajan: "राजन",
  rajesh: "राजेश",
  rakesh: "राकेश",
  ravindra: "रवींद्र",
  ravi: "रवि",
  rohit: "रोहित",
  rahul: "राहुल",
  ramesh: "रमेश",
  raman: "रमन",
  randhir: "रणधीर",
  ranjit: "रंजीत",
  rishabh: "ऋषभ",
  sanjay: "संजय",
  sunil: "सुनील",
  sudhir: "सुधीर",
  santosh: "संतोष",
  sushil: "सुशील",
  satish: "सतीश",
  surendra: "सुरेंद्र",
  sachin: "सचिन",
  saurabh: "सौरभ",
  shiv: "शिव",
  shankar: "शंकर",
  shyam: "श्याम",
  shatrughan: "शत्रुघ्न",
  tejashwi: "तेजस्वी",
  tarun: "तरुण",
  tushar: "तुषार",
  umesh: "उमेश",
  upendra: "उपेंद्र",
  vikas: "विकास",
  vikash: "विकास",
  vijay: "विजय",
  vishal: "विशाल",
  vinod: "विनोद",
  vipin: "विपिन",
  vivek: "विवेक",
  vidya: "विद्या",
  yogesh: "योगेश",
  yash: "यश",
  ajay: "अजय",
  akash: "आकाश",
  alok: "आलोक",
  amarnath: "अमरनाथ",
  amitabh: "अमिताभ",
  anand: "आनंद",
  aniket: "अनिकेत",
  ankur: "अंकुर",
  anoop: "अनूप",
  anuj: "अनुज",
  arvind: "अरविंद",
  atul: "अतुल",
  avinash: "अविनाश",
  badal: "बादल",
  bijay: "विजय",
  bikash: "विकास",
  bipin: "विपिन",
  birju: "बिरजू",
  brijesh: "बृजेश",
  brajesh: "ब्रजेश",
  budhram: "बुधराम",
  chandrakant: "चंद्रकांत",
  chirag: "चिराग",
  deepu: "दीपू",
  dhiru: "धीरू",
  dhruv: "ध्रुव",
  dipu: "दीपू",
  diwakar: "दिवाकर",
  gajendra: "गजेंद्र",
  girish: "गिरीश",
  govind: "गोविंद",
  gyanchand: "ज्ञानचंद",
  gyandeo: "ज्ञानदेव",
  hemant: "हेमंत",
  hemraj: "हेमराज",
  jagannath: "जगन्नाथ",
  jagmohan: "जगमोहन",
  jaiprakash: "जयप्रकाश",
  janardan: "जनार्दन",
  jeevan: "जीवन",
  jitesh: "जितेश",
  kailash: "कैलाश",
  kamlesh: "कमलेश",
  kamod: "कामोद",
  kartikey: "कार्तिकेय",
  kedar: "केदार",
  krishnakant: "कृष्णकांत",
  lalbahadur: "लालबहादुर",
  laxmikant: "लक्ष्मीकांत",
  lokesh: "लोकेश",
  madhav: "माधव",
  mahavir: "महावीर",
  mahesh: "महेश",
  manmohan: "मनमोहन",
  manohar: "मनोहर",
  mithun: "मिथुन",
  mithilesh: "मिथिलेश",
  mukundlal: "मुकुंदलाल",
  nagendra: "नागेंद्र",
  naresh: "नरेश",
  nathuni: "नथुनी",
  nayan: "नयन",
  nikhil: "निखिल",
  nilesh: "नीलेश",
  niranjan: "निरंजन",
  nirbhay: "निर्भय",
  prabhat: "प्रभात",
  prabhunath: "प्रभुनाथ",
  prahlad: "प्रह्लाद",
  rajdeo: "राजदेव",
  rajiv: "राजीव",
  rajkumar: "राजकुमार",
  rajnath: "राजनाथ",
  ramsagar: "रामसागर",
  ravishankar: "रविशंकर",
  sachchidanand: "सच्चिदानंद",
  sarvesh: "सर्वेश",
  satyendra: "सत्येंद्र",
  shalendra: "शैलेंद्र",
  shailendra: "शैलेंद्र",
  shambhu: "शंभू",
  shashi: "शशि",
  siddharth: "सिद्धार्थ",
  subbash: "सुभाष",
  subhash: "सुभाष",
  subodh: "सुबोध",
  subrat: "सुब्रत",
  sudama: "सुदामा",
  surajbali: "सूरजबली",
  surajdev: "सूरजदेव",
  suresh: "सुरेश",
  suryakant: "सूर्यकांत",
  swadesh: "स्वदेश",
  tribhuvan: "त्रिभुवन",
  uday: "उदय",
  umakant: "उमाकांत",
  vimal: "विमल",
  vinay: "विनय",
  vishnu: "विष्णु",
  yadunath: "यदुनाथ",
  yogendra: "योगेंद्र",
  yugalkishor: "युगलकिशोर",

  // ── Female First Names ─────────────────────────────────────
  anita: "अनीता",
  anjali: "अंजलि",
  arti: "आरती",
  aarti: "आरती",
  asha: "आशा",
  babita: "बबीता",
  bindu: "बिंदु",
  champa: "चंपा",
  chanda: "चंदा",
  deepa: "दीपा",
  divya: "दिव्या",
  geeta: "गीता",
  gauri: "गौरी",
  gayatri: "गायत्री",
  hema: "हेमा",
  indu: "इंदु",
  jyoti: "ज्योति",
  kavita: "कविता",
  kiran: "किरण",
  komal: "कोमल",
  kusum: "कुसुम",
  kalyani: "कल्याणी",
  lata: "लता",
  lalita: "ललिता",
  laxmi: "लक्ष्मी",
  lakshmi: "लक्ष्मी",
  mamta: "ममता",
  meena: "मीना",
  mina: "मीना",
  maya: "माया",
  manju: "मंजु",
  madhu: "मधु",
  mala: "माला",
  mona: "मोना",
  neha: "नेहा",
  neelam: "नीलम",
  nisha: "निशा",
  nibha: "निभा",
  pooja: "पूजा",
  puja: "पूजा",
  poonam: "पूनम",
  punam: "पूनम",
  pinky: "पिंकी",
  pushpa: "पुष्पा",
  priya: "प्रिया",
  priyanka: "प्रियंका",
  radha: "राधा",
  rakhi: "राखी",
  rekha: "रेखा",
  rani: "रानी",
  renu: "रेणु",
  reeta: "रीता",
  rita: "रीता",
  ruby: "रूबी",
  rupa: "रूपा",
  rima: "रीमा",
  sita: "सीता",
  sunita: "सुनीता",
  suman: "सुमन",
  sangita: "संगीता",
  sangeeta: "संगीता",
  savita: "सविता",
  sebah: "सबाह",
  sarita: "सरिता",
  sneha: "स्नेहा",
  soni: "सोनी",
  shanti: "शांति",
  shobha: "शोभा",
  shila: "शीला",
  sheela: "शीला",
  saraswati: "सरस्वती",
  shweta: "श्वेता",
  sima: "सीमा",
  seema: "सीमा",
  tara: "तारा",
  uma: "उमा",
  usha: "उषा",
  vandana: "वंदना",
  veena: "वीणा",
  yasoda: "यशोदा",
  yashoda: "यशोदा",
  abha: "आभा",
  achala: "अचला",
  aditi: "अदिति",
  aishwarya: "ऐश्वर्या",
  amita: "अमिता",
  amrita: "अमृता",
  archana: "अर्चना",
  aruna: "अरुणा",
  avantika: "अवंतिका",
  beena: "बीना",
  bela: "बेला",
  bhavna: "भावना",
  chandni: "चाँदनी",
  chandrika: "चंद्रिका",
  chhaya: "छाया",
  damyanti: "दमयंती",
  draupadi: "द्रौपदी",
  durga: "दुर्गा",
  garima: "गरिमा",
  gita: "गीता",
  hemlata: "हेमलता",
  indira: "इंदिरा",
  jahnavi: "जाह्नवी",
  janki: "जानकी",
  kamala: "कमला",
  kamini: "कामिनी",
  kanchan: "कंचन",
  kavya: "काव्या",
  khushbu: "खुशबू",
  kirna: "किरणा",
  kumkum: "कुमकुम",
  latika: "लतिका",
  leela: "लीला",
  lila: "लीला",
  madhuri: "माधुरी",
  malti: "मालती",
  manisha: "मनीषा",
  manjula: "मंजुला",
  meenakshi: "मीनाक्षी",
  menka: "मेनका",
  minakshi: "मीनाक्षी",
  nandita: "नंदिता",
  narayan_devi: "नारायण देवी",
  nirmala: "निर्मला",
  nitu: "नीतू",
  prabha: "प्रभा",
  pratibha: "प्रतिभा",
  preeti: "प्रीति",
  premlata: "प्रेमलता",
  prity: "प्रीति",
  pushpalata: "पुष्पलता",
  ragini: "रागिनी",
  rajeshwari: "राजेश्वरी",
  rajkumari: "राजकुमारी",
  rajrani: "राजरानी",
  ranjeeta: "रंजीता",
  ratna: "रत्ना",
  renuka: "रेणुका",
  sadhana: "साधना",
  sarita2: "सरिता",
  sarla: "सरला",
  savitri: "सावित्री",
  shakuntala: "शकुंतला",
  shakti: "शक्ति",
  sharada: "शारदा",
  sharadha: "शारदा",
  sharmila: "शर्मिला",
  shikha: "शिखा",
  shipra: "शिप्रा",
  shruti: "श्रुति",
  shushma: "सुषमा",
  sushma: "सुषमा",
  sonali: "सोनाली",
  soniya: "सोनिया",
  sonu: "सोनू",
  subhadra: "सुभद्रा",
  sulekha: "सुलेखा",
  sumitra: "सुमित्रा",
  sunaina: "सुनैना",
  suneeta: "सुनीता",
  surbhi: "सुरभि",
  swati: "स्वाति",
  tanuja: "तनुजा",
  tanushree: "तनुश्री",
  trisna: "तृष्णा",
  urmila: "उर्मिला",
  vimla: "विमला",
  vimladevi: "विमला देवी",
  vrinda: "वृंदा",
  yamuna: "यमुना",
  yogmaya: "योगमाया",

  // ── Surnames / Castes / Communities ───────────────────────
  ali: "अली",
  ahmad: "अहमद",
  ahmed: "अहमद",
  ansari: "अंसारी",
  bhagat: "भगत",
  bharti: "भारती",
  bhatt: "भट्ट",
  choudhary: "चौधरी",
  chaurasia: "चौरसिया",
  chauhan: "चौहान",
  dubey: "दुबे",
  dixit: "दीक्षित",
  gupta: "गुप्ता",
  giri: "गिरी",
  goswami: "गोस्वामी",
  hussain: "हुसैन",
  hasan: "हसन",
  jain: "जैन",
  kumari: "कुमारी",
  kaur: "कौर",
  khatoon: "खातून",
  khan: "खान",
  lal: "लाल",
  mahto: "महतो",
  mahato: "महतो",
  majhi: "माझी",
  mallick: "मल्लिक",
  mukherjee: "मुखर्जी",
  narayan: "नारायण",
  nath: "नाथ",
  ojha: "ओझा",
  pandey: "पांडेय",
  patel: "पटेल",
  pathak: "पाठक",
  prakash: "प्रकाश",
  roy: "रॉय",
  ray: "राय",
  rao: "राव",
  rajput: "राजपूत",
  rout: "राउत",
  raut: "राउत",
  sahni: "सहनी",
  srivastava: "श्रीवास्तव",
  sinha: "सिन्हा",
  saha: "साहा",
  sheikh: "शेख",
  shukla: "शुक्ला",
  swami: "स्वामी",
  shroff: "श्रॉफ",
  tiwari: "तिवारी",
  trivedi: "त्रिवेदी",
  upadhyay: "उपाध्याय",
  verma: "वर्मा",
  bano: "बानो",
  bibi: "बीबी",
  dev: "देव",
  ji: "जी",
  kant: "कांत",
  mian: "मियां",
  pratap: "प्रताप",
  ratan: "रतन",
  sahay: "सहाय",
  sinh: "सिंह",
  kushwaha: "कुशवाहा",
  koiri: "कोइरी",
  koyri: "कोइरी",
  mehta: "मेहता",
  kurmi: "कुर्मी",
  bhumihar: "भूमिहार",
  brahmin: "ब्राह्मण",
  baman: "बामन",
  pandit: "पंडित",
  ahir: "अहीर",
  gwala: "ग्वाला",
  dhobi: "धोबी",
  dusadh: "दुसाध",
  chamar: "चमार",
  ravidas: "रविदास",
  mochi: "मोची",
  mushar: "मुसहर",
  musahar: "मुसहर",
  teli: "तेली",
  suri: "सूरी",
  baniya: "बनिया",
  kalwar: "कलवार",
  sonar: "सोनार",
  lohar: "लोहार",
  barhai: "बढ़ई",
  nai: "नाई",
  hajam: "हज्जाम",
  mali: "माली",
  nuniya: "नोनिया",
  noniya: "नोनिया",
  bind: "बिंद",
  mallah: "मल्लाह",
  nishad: "निषाद",
  choubey: "चौबे",
  dube: "दुबे",
  vishwakarma: "विश्वकर्मा",
  seth: "सेठ",
  rathore: "राठौर",
  sen: "सेन",
  bose: "बोस",
  shrivastava: "श्रीवास्तव",
  saurav: "सौरव",
  kevat: "केवट",
  kewat: "केवट",
  rajbhar: "राजभर",
  rajbhangi: "राजभाँगी",
  dom: "डोम",
  nut: "नट",
  nat: "नट",
  kayastha: "कायस्थ",
  kshatriya: "क्षत्रिय",
  vaishya: "वैश्य",
  shudra: "शूद्र",
  hatwa: "हटवा",
  halwai: "हलवाई",
  kumhar: "कुम्हार",
  tamoli: "तमोली",
  musalman: "मुसलमान",
  hindu: "हिंदू",
  muslim: "मुस्लिम",
  christian: "ईसाई",
  isai: "ईसाई",

  // ── Compound Names (Kishor / Kumar / Nath etc.) ────────────
  harikishor: "हरिकिशोर",
  harikishore: "हरिकिशोर",
  rajkishor: "राजकिशोर",
  rajkishore: "राजकिशोर",
  brajkishor: "ब्रजकिशोर",
  brajkishore: "ब्रजकिशोर",
  nandkishor: "नंदकिशोर",
  nandkishore: "नंदकिशोर",
  ramkishor: "रामकिशोर",
  ramkishore: "रामकिशोर",
  yugalkishore: "युगलकिशोर",
  nawalkishor: "नवलकिशोर",
  nawalkishore: "नवलकिशोर",
  shivkishor: "शिवकिशोर",
  shivkishore: "शिवकिशोर",
  awal: "अवल",
  shivkumar: "शिवकुमार",
  ramkumar: "रामकुमार",
  krishnakumar: "कृष्णकुमार",
  nandkumar: "नंदकुमार",
  ramanandan: "रामनंदन",
  shivnandan: "शिवनंदन",
  raghunandan: "रघुनंदन",
  krishnanandan: "कृष्णनंदन",
  yugalnandan: "युगलनंदन",
  ramnath: "रामनाथ",
  shivnath: "शिवनाथ",
  baidyanath: "बैद्यनाथ",
  dinanath: "दीनानाथ",
  kashinath: "काशीनाथ",
  vishwanath: "विश्वनाथ",
  ramprasad: "रामप्रसाद",
  shivprasad: "शिवप्रसाद",
  hariprasad: "हरिप्रसाद",
  rajendraprasad: "राजेंद्रप्रसाद",
  ramnarayan: "रामनारायण",
  shivnarayan: "शिवनारायण",
  suryanarayan: "सूर्यनारायण",
  satyanarayan: "सत्यनारायण",
  uditnarayan: "उदितनारायण",
  ramashray: "रामाश्रय",
  shivashray: "शिवाश्रय",
  ramachandra: "रामचंद्र",
  ramchandra: "रामचंद्र",
  krishnachandra: "कृष्णचंद्र",
  radhamohan: "राधामोहन",
  krishnamohan: "कृष्णमोहन",
  ramlakhan: "रामलखन",
  ramlakshman: "रामलक्ष्मण",
  hariom: "हरिओम",
  ramji: "रामजी",
  ramjas: "रामजस",
  rambriksha: "रामबृक्ष",
  ramsevak: "रामसेवक",
  ramdeo: "रामदेव",
  ramdayal: "रामदयाल",
  baidyanathdham: "बैद्यनाथधाम",
  bindeshwari: "बिंदेश्वरी",
  kameshwari: "कामेश्वरी",
  parmeshwari: "परमेश्वरी",
  rameshwari: "रामेश्वरी",
  bhuneshwar: "भुवनेश्वर",
  bhuvaneshwar: "भुवनेश्वर",
  kameshwar: "कामेश्वर",
  parmeshwar: "परमेश्वर",
  kamesh: "कामेश",
  virendra: "वीरेंद्र",
  rajendra: "राजेंद्र",
  amarendra: "अमरेंद्र",
  samarendra: "समरेंद्र",
  akhilesh: "अखिलेश",
  vimlesh: "विमलेश",

  // ── Common Verbs / Action Words ─────────────────────────────
  hai: "है",
  hain: "हैं",
  tha: "था",
  thi: "थी",
  the: "थे",
  hoga: "होगा",
  hogi: "होगी",
  honge: "होंगे",
  karna: "करना",
  karo: "करो",
  kiya: "किया",
  ki: "की",
  ka: "का",
  ke: "के",
  ko: "को",
  se: "से",
  mein: "में",
  par: "पर",
  lena: "लेना",
  dena: "देना",
  aana: "आना",
  jaana: "जाना",
  milna: "मिलना",
  likhna: "लिखना",
  padhna: "पढ़ना",
  dekhna: "देखना",
  sunna: "सुनना",
  bolna: "बोलना",
  banana: "बनाना",
  batana: "बताना",
  chahna: "चाहना",
  samajhna: "समझना",
  chahiye: "चाहिए",
  pata: "पता",
  maloom: "मालूम",
  theek: "ठीक",
  sahi: "सही",
  galat: "गलत",
  nahi: "नहीं",
  haan: "हाँ",
  nahin: "नहीं",
  kya: "क्या",
  kab: "कब",
  kahan: "कहाँ",
  kyun: "क्यों",
  kyunki: "क्योंकि",
  isliye: "इसलिए",
  aur: "और",
  ya: "या",
  lekin: "लेकिन",
  magar: "मगर",
  phir: "फिर",
  toh: "तो",
  bhi: "भी",
  sirf: "सिर्फ",
  sab: "सब",
  koi: "कोई",
  kuch: "कुछ",
  bahut: "बहुत",
  thoda: "थोड़ा",
  zyada: "ज़्यादा",
  kam: "कम",
  jyada: "ज़्यादा",
  ab: "अब",
  tab: "तब",
  jab: "जब",
  yahan: "यहाँ",
  wahan: "वहाँ",
  idhar: "इधर",
  udhar: "उधर",
  upar: "ऊपर",
  neeche: "नीचे",
  andar: "अंदर",
  bahar: "बाहर",
  aage: "आगे",
  peeche: "पीछे",
  paas: "पास",
  dur: "दूर",
  sath: "साथ",
  bina: "बिना",
  wala: "वाला",
  wali: "वाली",
  wale: "वाले",
  jaisa: "जैसा",
  waisa: "वैसा",
  itna: "इतना",
  utna: "उतना",
  kitna: "कितना",
  pura: "पूरा",
  aadha: "आधा",
  ek: "एक",
  do: "दो",
  teen: "तीन",
  chaar: "चार",
  paanch: "पाँच",
  chhah: "छह",
  saat: "सात",
  aath: "आठ",
  nau: "नौ",
  das: "दस",
  bees: "बीस",
  pachas: "पचास",
  sau: "सौ",
  hazar: "हज़ार",
  lakh: "लाख",
  crore: "करोड़",

  // ── Months (Hindi / Gregorian) ──────────────────────────────
  january: "जनवरी",
  february: "फ़रवरी",
  march: "मार्च",
  april: "अप्रैल",
  may: "मई",
  june: "जून",
  july: "जुलाई",
  august: "अगस्त",
  september: "सितंबर",
  october: "अक्टूबर",
  november: "नवंबर",
  december: "दिसंबर",
  chaitra: "चैत्र",
  vaishakh: "वैशाख",
  jyeshtha: "ज्येष्ठ",
  ashadh: "आषाढ़",
  shravan: "श्रावण",
  bhadra: "भाद्रपद",
  ashwin: "आश्विन",
  kartik: "कार्तिक",
  margashirsha: "मार्गशीर्ष",
  paush: "पौष",
  magh: "माघ",
  falgun: "फाल्गुन",

  // ── Days of Week ────────────────────────────────────────────
  sunday: "रविवार",
  monday: "सोमवार",
  tuesday: "मंगलवार",
  wednesday: "बुधवार",
  thursday: "गुरुवार",
  friday: "शुक्रवार",
  saturday: "शनिवार",
  ravivar: "रविवार",
  somvar: "सोमवार",
  mangalvar: "मंगलवार",
  budhvar: "बुधवार",
  guruvar: "गुरुवार",
  shukravar: "शुक्रवार",
  shanivar: "शनिवार",

  // ── Religious / Cultural Terms ──────────────────────────────
  mandir: "मंदिर",
  masjid: "मस्जिद",
  girja: "गिरजा",
  gurudwara: "गुरुद्वारा",
  namaz: "नमाज़",
  prayer: "प्रार्थना",
  prarthana: "प्रार्थना",
  prasad2: "प्रसाद",
  bhog: "भोग",
  tilak: "तिलक",
  tika: "टीका",
  pujari: "पुजारी",
  maulvi: "मौलवी",
  imam: "इमाम",
  panditji: "पंडितजी",
  bhagwan: "भगवान",
  allah: "अल्लाह",
  ishwar: "ईश्वर",
  bhagwat: "भागवत",
  ramayan: "रामायण",
  mahabharat: "महाभारत",
  quran: "कुरान",
  bible: "बाइबिल",
  dharm: "धर्म",
  dharma: "धर्म",
  karma: "कर्म",
  moksha: "मोक्ष",
  avatar: "अवतार",
  sadhu: "साधु",
  sant: "संत",
  mahatma: "महात्मा",
  rishi: "ऋषि",
  muni: "मुनि",
  yogi: "योगी",
  ashram: "आश्रम",
  akshay: "अक्षय",
  diwali: "दीवाली",
  holi: "होली",
  eid: "ईद",
  christmas: "क्रिसमस",
  janmashtami: "जन्माष्टमी",
  ramnavami: "रामनवमी",
  navratri: "नवरात्रि",
  durga_puja: "दुर्गा पूजा",
  chhath: "छठ",
  makar: "मकर",
  sankranti: "संक्रांति",

  // ── Common Nouns (Everyday) ─────────────────────────────────
  ghar: "घर",
  makaan: "मकान",
  dukaan: "दुकान",
  bazaar: "बाज़ार",
  raasta: "रास्ता",
  sadak: "सड़क",
  naali: "नाली",
  kuaan: "कुआँ",
  talab: "तालाब",
  nadi: "नदी",
  kheth: "खेत",
  khet: "खेत",
  jungle: "जंगल",
  pahaad: "पहाड़",
  maidan: "मैदान",
  chowk: "चौक",
  chauraaha: "चौराहा",
  pul: "पुल",
  nahar: "नहर",
  bandh: "बाँध",
  dam: "बाँध",
  bijli: "बिजली",
  paani: "पानी",
  aag: "आग",
  hawa: "हवा",
  baarish: "बारिश",
  dhoop: "धूप",
  chaanv: "छाँव",
  raat: "रात",
  subah: "सुबह",
  shaam: "शाम",
  dopahar: "दोपहर",
  baat: "बात",
  kaam: "काम",
  paisa2: "पैसा",
  rupaya: "रुपया",
  rupees: "रुपये",
  roti: "रोटी",
  chawal: "चावल",
  daal: "दाल",
  sabzi: "सब्जी",
  dudh: "दूध",
  tel: "तेल",
  namak: "नमक",
  chini: "चीनी",
  aata: "आटा",
  kapda: "कपड़ा",
  juta: "जूता",
  gaddi: "गाड़ी",
  gaadi: "गाड़ी",
  cycle: "साइकिल",
  tractor: "ट्रैक्टर",
  naav: "नाव",
  hawai: "हवाई",
  jahaaz: "जहाज़",
  hospital: "अस्पताल",
  aspataal: "अस्पताल",
  school: "स्कूल",
  vidyalay: "विद्यालय",
  college: "कॉलेज",
  university: "विश्वविद्यालय",
  bank: "बैंक",
  police: "पुलिस",
  station: "स्टेशन",
  airport: "हवाई अड्डा",
  railway: "रेलवे",
  road: "सड़क",
  highway: "राजमार्ग",

};

// ─────────────────────────────────────────────────────────────
// 2. PHONETIC MAPS  (same as original — do not alter)
// ─────────────────────────────────────────────────────────────

export const consonants: Record<string, string> = {
  ksh: "क्ष",
  gya: "ज्ञ",
  gy: "ज्ञ",
  shr: "श्र",
  kh: "ख",
  gh: "घ",
  chh: "छ",
  ch: "च",
  jh: "झ",
  th: "थ",
  dh: "ध",
  ph: "फ",
  bh: "भ",
  sh: "श",
  tr: "त्र",
  k: "क",
  q: "क",
  g: "ग",
  c: "क",
  j: "ज",
  z: "ज",
  t: "त",
  d: "द",
  n: "न",
  p: "प",
  f: "फ",
  b: "ब",
  m: "म",
  y: "य",
  r: "र",
  l: "ल",
  v: "व",
  w: "व",
  s: "स",
  h: "ह",
};

export const independentVowels: Record<string, string> = {
  aa: "आ",
  ai: "ऐ",
  au: "औ",
  ee: "ई",
  ii: "ई",
  oo: "ऊ",
  a: "अ",
  i: "इ",
  u: "उ",
  e: "ए",
  o: "ओ",
};

export const vowelMarks: Record<string, string> = {
  aa: "ा",
  ai: "ै",
  au: "ौ",
  ee: "ी",
  ii: "ी",
  oo: "ू",
  a: "",
  i: "ि",
  u: "ु",
  e: "े",
  o: "ो",
};

// ─────────────────────────────────────────────────────────────
// 3. CORE TRANSLITERATION ENGINE  (preserved from original)
// ─────────────────────────────────────────────────────────────

const consonantKeys = Object.keys(consonants).sort((a, b) => b.length - a.length);
const vowelKeys = Object.keys(independentVowels).sort((a, b) => b.length - a.length);

function nextToken(
  source: string,
  index: number,
  map: Record<string, string>,
  keys: string[]
): { key: string; value: string } | null {
  for (const key of keys) {
    if (source.startsWith(key, index)) {
      return { key, value: map[key] };
    }
  }
  return null;
}

function hasNextVowel(source: string, index: number): boolean {
  return Boolean(nextToken(source, index, independentVowels, vowelKeys));
}

function splitWord(word: string): { latin: string; suffix: string } {
  const match = word.match(/^([A-Za-z]+)([^A-Za-z]*)$/);
  return {
    latin: match?.[1] ?? "",
    suffix: match?.[2] ?? "",
  };
}

/**
 * Transliterate a single Latin word to Devanagari.
 * Pure Hindi / Devanagari strings and numbers pass through unchanged.
 */
export function transliterateWord(word: string): string {
  if (!word || /[\u0900-\u097F]/.test(word) || /^\d+(\.\d+)?$/.test(word)) {
    return word;
  }

  const { latin, suffix } = splitWord(word);
  if (!latin) return word;

  const lower = latin.toLowerCase();
  if (directWords[lower]) {
    return `${directWords[lower]}${suffix}`;
  }

  let index = 0;
  let output = "";

  while (index < lower.length) {
    const consonant = nextToken(lower, index, consonants, consonantKeys);

    if (consonant) {
      output += consonant.value;
      index += consonant.key.length;

      const vowel = nextToken(lower, index, vowelMarks, vowelKeys);
      if (vowel) {
        output += vowel.value;
        index += vowel.key.length;
      } else if (index < lower.length && !hasNextVowel(lower, index)) {
        output += "्";
      }
      continue;
    }

    const vowel = nextToken(lower, index, independentVowels, vowelKeys);
    if (vowel) {
      output += vowel.value;
      index += vowel.key.length;
      continue;
    }

    output += latin[index];
    index += 1;
  }

  return `${output}${suffix}`;
}

/**
 * Transliterate the last word in a string when the user types a space.
 * Useful for live / real-time input fields.
 */
export function transliterateTrailingWord(value: string): string {
  if (!value.endsWith(" ")) return value;

  const withoutSpace = value.slice(0, -1);
  const match = withoutSpace.match(/(\S+)$/);
  if (!match) return value;

  const word = match[1];
  const start = withoutSpace.slice(0, -word.length);

  return `${start}${transliterateWord(word)} `;
}

/**
 * Transliterate an entire space-separated string.
 * Punctuation attached to words is preserved.
 */
export function transliterateText(text: string): string {
  if (!text) return text;
  return text
    .split(/(\s+)/)
    .map(token => (/\s/.test(token) ? token : transliterateWord(token)))
    .join("");
}

/**
 * Lookup a term directly from the dictionary (case-insensitive).
 * Returns undefined if not found.
 */
export function lookup(term: string): string | undefined {
  return directWords[term.toLowerCase().trim()];
}

/**
 * Returns all dictionary entries that contain the given substring (case-insensitive).
 * Useful for building autocomplete / suggestion features.
 */
export function search(query: string): Array<{ latin: string; hindi: string }> {
  const q = query.toLowerCase().trim();
  return Object.entries(directWords)
    .filter(([key]) => key.includes(q))
    .map(([latin, hindi]) => ({ latin, hindi }));
}